name: Deploy to EC2

on:
  push:
    branches: 
      - main
      - "release/*"  # release/0.0.1, release/v1 등 모든 release 브랜치 허용

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          # host: "3.144.75.223"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/workspace/upstage-network-lecture
            git pull origin main
            # 기존 프로세스 종료 (8000포트 사용 중인 프로세스)
            fuser -k 8000/tcp || true
            # uv 환경에서 서버 백그라운드 실행
            nohup uv run uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &